# Generated by Django 4.2.6 on 2023-10-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('wallet', models.FloatField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
