# Generated by Django 4.2.7 on 2023-11-22 14:48

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellitems',
            name='picture',
            field=models.ImageField(default='defaults/default_product.png', null=True, upload_to=base.models.profile_img),
        ),
    ]
